% \VignetteIndexEntry{XX}
% \VignettePackage{minfi}
% \VignetteDepends{BiocStyle}
% \VignetteEngine{knitr::knitr}

\documentclass{article}

<<style, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex()
@ 

\title{The minfi user's guide}
\author{Kasper D.\ Hansen \and Jean-Phillipe Fortin}
\date{Modified: October 20, 2013.  Compiled: \today}

\begin{document}

\maketitle

\tableofcontents

\section{Introduction}

A brief overview of minfi.

This will include a 10 line analysis.

\section{Reading data}

This will be tedious, but it is important

\section{Data classes in minfi}

Here I will write about the 5 basic classes in minfi for representing data

\section{Quality control}

Short, but with pointers to shiny methyl of course.

\section{Dealing with SNPs}

Short, but important.

\section{Normalization}

Overview of normalization.

\section{Bump hunting}

How to do a bump hunting analysis.

\section{Using annotation}

\section{Other stuff}




\section{Session info}

Here is the output of \Rfunction{sessionInfo} on the system on which
this document was compiled:
<<sessionInfo, results="asis", print=TRUE, eval=TRUE>>=
toLatex(sessionInfo())
@

\nocite{*}
\bibliography{minfi}

\end{document}
